[package]
name = "image_processor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
plotters = "0.3.6"
show-image = "=0.10.1"
rustfft = "6.2.0"
